#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Service
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NSNP_Database")]
	public partial class DataConnectionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertA_Report(A_Report instance);
    partial void UpdateA_Report(A_Report instance);
    partial void DeleteA_Report(A_Report instance);
    partial void InsertAreaOffice(AreaOffice instance);
    partial void UpdateAreaOffice(AreaOffice instance);
    partial void DeleteAreaOffice(AreaOffice instance);
    partial void InsertAreaSchoolMessage(AreaSchoolMessage instance);
    partial void UpdateAreaSchoolMessage(AreaSchoolMessage instance);
    partial void DeleteAreaSchoolMessage(AreaSchoolMessage instance);
    partial void InsertD_Report(D_Report instance);
    partial void UpdateD_Report(D_Report instance);
    partial void DeleteD_Report(D_Report instance);
    partial void InsertDistrict(District instance);
    partial void UpdateDistrict(District instance);
    partial void DeleteDistrict(District instance);
    partial void InsertDistrictAreaMessage(DistrictAreaMessage instance);
    partial void UpdateDistrictAreaMessage(DistrictAreaMessage instance);
    partial void DeleteDistrictAreaMessage(DistrictAreaMessage instance);
    partial void InsertFileInformation(FileInformation instance);
    partial void UpdateFileInformation(FileInformation instance);
    partial void DeleteFileInformation(FileInformation instance);
    partial void InsertProvincial(Provincial instance);
    partial void UpdateProvincial(Provincial instance);
    partial void DeleteProvincial(Provincial instance);
    partial void InsertS_Report(S_Report instance);
    partial void UpdateS_Report(S_Report instance);
    partial void DeleteS_Report(S_Report instance);
    partial void InsertSchool(School instance);
    partial void UpdateSchool(School instance);
    partial void DeleteSchool(School instance);
    partial void InsertLogin(Login instance);
    partial void UpdateLogin(Login instance);
    partial void DeleteLogin(Login instance);
    #endregion
		
		public DataConnectionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NSNP_DatabaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<A_Report> A_Reports
		{
			get
			{
				return this.GetTable<A_Report>();
			}
		}
		
		public System.Data.Linq.Table<AreaOffice> AreaOffices
		{
			get
			{
				return this.GetTable<AreaOffice>();
			}
		}
		
		public System.Data.Linq.Table<AreaSchoolMessage> AreaSchoolMessages
		{
			get
			{
				return this.GetTable<AreaSchoolMessage>();
			}
		}
		
		public System.Data.Linq.Table<D_Report> D_Reports
		{
			get
			{
				return this.GetTable<D_Report>();
			}
		}
		
		public System.Data.Linq.Table<District> Districts
		{
			get
			{
				return this.GetTable<District>();
			}
		}
		
		public System.Data.Linq.Table<DistrictAreaMessage> DistrictAreaMessages
		{
			get
			{
				return this.GetTable<DistrictAreaMessage>();
			}
		}
		
		public System.Data.Linq.Table<FileInformation> FileInformations
		{
			get
			{
				return this.GetTable<FileInformation>();
			}
		}
		
		public System.Data.Linq.Table<Provincial> Provincials
		{
			get
			{
				return this.GetTable<Provincial>();
			}
		}
		
		public System.Data.Linq.Table<S_Report> S_Reports
		{
			get
			{
				return this.GetTable<S_Report>();
			}
		}
		
		public System.Data.Linq.Table<School> Schools
		{
			get
			{
				return this.GetTable<School>();
			}
		}
		
		public System.Data.Linq.Table<Login> Logins
		{
			get
			{
				return this.GetTable<Login>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_Report")]
	public partial class A_Report : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _R_ID;
		
		private string _Month;
		
		private System.Nullable<System.DateTime> _Submission_Date;
		
		private System.Nullable<double> _BankCharges;
		
		private System.Nullable<double> _Allocation;
		
		private System.Nullable<double> _Expenditure;
		
		private System.Nullable<double> _Balance;
		
		private string _A_No;
		
		private System.Nullable<int> _Schools_Submitted;
		
		private EntityRef<AreaOffice> _AreaOffice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnR_IDChanging(int value);
    partial void OnR_IDChanged();
    partial void OnMonthChanging(string value);
    partial void OnMonthChanged();
    partial void OnSubmission_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnSubmission_DateChanged();
    partial void OnBankChargesChanging(System.Nullable<double> value);
    partial void OnBankChargesChanged();
    partial void OnAllocationChanging(System.Nullable<double> value);
    partial void OnAllocationChanged();
    partial void OnExpenditureChanging(System.Nullable<double> value);
    partial void OnExpenditureChanged();
    partial void OnBalanceChanging(System.Nullable<double> value);
    partial void OnBalanceChanged();
    partial void OnA_NoChanging(string value);
    partial void OnA_NoChanged();
    partial void OnSchools_SubmittedChanging(System.Nullable<int> value);
    partial void OnSchools_SubmittedChanged();
    #endregion
		
		public A_Report()
		{
			this._AreaOffice = default(EntityRef<AreaOffice>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int R_ID
		{
			get
			{
				return this._R_ID;
			}
			set
			{
				if ((this._R_ID != value))
				{
					this.OnR_IDChanging(value);
					this.SendPropertyChanging();
					this._R_ID = value;
					this.SendPropertyChanged("R_ID");
					this.OnR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="VarChar(50)")]
		public string Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this.OnMonthChanging(value);
					this.SendPropertyChanging();
					this._Month = value;
					this.SendPropertyChanged("Month");
					this.OnMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Submission_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Submission_Date
		{
			get
			{
				return this._Submission_Date;
			}
			set
			{
				if ((this._Submission_Date != value))
				{
					this.OnSubmission_DateChanging(value);
					this.SendPropertyChanging();
					this._Submission_Date = value;
					this.SendPropertyChanged("Submission_Date");
					this.OnSubmission_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankCharges", DbType="Float")]
		public System.Nullable<double> BankCharges
		{
			get
			{
				return this._BankCharges;
			}
			set
			{
				if ((this._BankCharges != value))
				{
					this.OnBankChargesChanging(value);
					this.SendPropertyChanging();
					this._BankCharges = value;
					this.SendPropertyChanged("BankCharges");
					this.OnBankChargesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Allocation", DbType="Float")]
		public System.Nullable<double> Allocation
		{
			get
			{
				return this._Allocation;
			}
			set
			{
				if ((this._Allocation != value))
				{
					this.OnAllocationChanging(value);
					this.SendPropertyChanging();
					this._Allocation = value;
					this.SendPropertyChanged("Allocation");
					this.OnAllocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expenditure", DbType="Float")]
		public System.Nullable<double> Expenditure
		{
			get
			{
				return this._Expenditure;
			}
			set
			{
				if ((this._Expenditure != value))
				{
					this.OnExpenditureChanging(value);
					this.SendPropertyChanging();
					this._Expenditure = value;
					this.SendPropertyChanged("Expenditure");
					this.OnExpenditureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Float")]
		public System.Nullable<double> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this.OnBalanceChanging(value);
					this.SendPropertyChanging();
					this._Balance = value;
					this.SendPropertyChanged("Balance");
					this.OnBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_No", DbType="VarChar(50)")]
		public string A_No
		{
			get
			{
				return this._A_No;
			}
			set
			{
				if ((this._A_No != value))
				{
					if (this._AreaOffice.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnA_NoChanging(value);
					this.SendPropertyChanging();
					this._A_No = value;
					this.SendPropertyChanged("A_No");
					this.OnA_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Schools_Submitted", DbType="Int")]
		public System.Nullable<int> Schools_Submitted
		{
			get
			{
				return this._Schools_Submitted;
			}
			set
			{
				if ((this._Schools_Submitted != value))
				{
					this.OnSchools_SubmittedChanging(value);
					this.SendPropertyChanging();
					this._Schools_Submitted = value;
					this.SendPropertyChanged("Schools_Submitted");
					this.OnSchools_SubmittedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AreaOffice_A_Report", Storage="_AreaOffice", ThisKey="A_No", OtherKey="A_No", IsForeignKey=true)]
		public AreaOffice AreaOffice
		{
			get
			{
				return this._AreaOffice.Entity;
			}
			set
			{
				AreaOffice previousValue = this._AreaOffice.Entity;
				if (((previousValue != value) 
							|| (this._AreaOffice.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AreaOffice.Entity = null;
						previousValue.A_Reports.Remove(this);
					}
					this._AreaOffice.Entity = value;
					if ((value != null))
					{
						value.A_Reports.Add(this);
						this._A_No = value.A_No;
					}
					else
					{
						this._A_No = default(string);
					}
					this.SendPropertyChanged("AreaOffice");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AreaOffice")]
	public partial class AreaOffice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _A_No;
		
		private string _A_Name;
		
		private string _A_Email;
		
		private string _D_No;
		
		private string _A_Cellphone;
		
		private string _A_Tellphone;
		
		private string _A_Manager;
		
		private System.Nullable<int> _A_NumSchools;
		
		private EntitySet<A_Report> _A_Reports;
		
		private EntitySet<AreaSchoolMessage> _AreaSchoolMessages;
		
		private EntitySet<School> _Schools;
		
		private EntityRef<District> _District;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnA_NoChanging(string value);
    partial void OnA_NoChanged();
    partial void OnA_NameChanging(string value);
    partial void OnA_NameChanged();
    partial void OnA_EmailChanging(string value);
    partial void OnA_EmailChanged();
    partial void OnD_NoChanging(string value);
    partial void OnD_NoChanged();
    partial void OnA_CellphoneChanging(string value);
    partial void OnA_CellphoneChanged();
    partial void OnA_TellphoneChanging(string value);
    partial void OnA_TellphoneChanged();
    partial void OnA_ManagerChanging(string value);
    partial void OnA_ManagerChanged();
    partial void OnA_NumSchoolsChanging(System.Nullable<int> value);
    partial void OnA_NumSchoolsChanged();
    #endregion
		
		public AreaOffice()
		{
			this._A_Reports = new EntitySet<A_Report>(new Action<A_Report>(this.attach_A_Reports), new Action<A_Report>(this.detach_A_Reports));
			this._AreaSchoolMessages = new EntitySet<AreaSchoolMessage>(new Action<AreaSchoolMessage>(this.attach_AreaSchoolMessages), new Action<AreaSchoolMessage>(this.detach_AreaSchoolMessages));
			this._Schools = new EntitySet<School>(new Action<School>(this.attach_Schools), new Action<School>(this.detach_Schools));
			this._District = default(EntityRef<District>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_No", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string A_No
		{
			get
			{
				return this._A_No;
			}
			set
			{
				if ((this._A_No != value))
				{
					this.OnA_NoChanging(value);
					this.SendPropertyChanging();
					this._A_No = value;
					this.SendPropertyChanged("A_No");
					this.OnA_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_Name", DbType="VarChar(50)")]
		public string A_Name
		{
			get
			{
				return this._A_Name;
			}
			set
			{
				if ((this._A_Name != value))
				{
					this.OnA_NameChanging(value);
					this.SendPropertyChanging();
					this._A_Name = value;
					this.SendPropertyChanged("A_Name");
					this.OnA_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_Email", DbType="VarChar(50)")]
		public string A_Email
		{
			get
			{
				return this._A_Email;
			}
			set
			{
				if ((this._A_Email != value))
				{
					this.OnA_EmailChanging(value);
					this.SendPropertyChanging();
					this._A_Email = value;
					this.SendPropertyChanged("A_Email");
					this.OnA_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_No", DbType="VarChar(50)")]
		public string D_No
		{
			get
			{
				return this._D_No;
			}
			set
			{
				if ((this._D_No != value))
				{
					if (this._District.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnD_NoChanging(value);
					this.SendPropertyChanging();
					this._D_No = value;
					this.SendPropertyChanged("D_No");
					this.OnD_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_Cellphone", DbType="VarChar(50)")]
		public string A_Cellphone
		{
			get
			{
				return this._A_Cellphone;
			}
			set
			{
				if ((this._A_Cellphone != value))
				{
					this.OnA_CellphoneChanging(value);
					this.SendPropertyChanging();
					this._A_Cellphone = value;
					this.SendPropertyChanged("A_Cellphone");
					this.OnA_CellphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_Tellphone", DbType="VarChar(50)")]
		public string A_Tellphone
		{
			get
			{
				return this._A_Tellphone;
			}
			set
			{
				if ((this._A_Tellphone != value))
				{
					this.OnA_TellphoneChanging(value);
					this.SendPropertyChanging();
					this._A_Tellphone = value;
					this.SendPropertyChanged("A_Tellphone");
					this.OnA_TellphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_Manager", DbType="VarChar(50)")]
		public string A_Manager
		{
			get
			{
				return this._A_Manager;
			}
			set
			{
				if ((this._A_Manager != value))
				{
					this.OnA_ManagerChanging(value);
					this.SendPropertyChanging();
					this._A_Manager = value;
					this.SendPropertyChanged("A_Manager");
					this.OnA_ManagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_NumSchools", DbType="Int")]
		public System.Nullable<int> A_NumSchools
		{
			get
			{
				return this._A_NumSchools;
			}
			set
			{
				if ((this._A_NumSchools != value))
				{
					this.OnA_NumSchoolsChanging(value);
					this.SendPropertyChanging();
					this._A_NumSchools = value;
					this.SendPropertyChanged("A_NumSchools");
					this.OnA_NumSchoolsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AreaOffice_A_Report", Storage="_A_Reports", ThisKey="A_No", OtherKey="A_No")]
		public EntitySet<A_Report> A_Reports
		{
			get
			{
				return this._A_Reports;
			}
			set
			{
				this._A_Reports.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AreaOffice_AreaSchoolMessage", Storage="_AreaSchoolMessages", ThisKey="A_No", OtherKey="A_No")]
		public EntitySet<AreaSchoolMessage> AreaSchoolMessages
		{
			get
			{
				return this._AreaSchoolMessages;
			}
			set
			{
				this._AreaSchoolMessages.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AreaOffice_School", Storage="_Schools", ThisKey="A_No", OtherKey="A_No")]
		public EntitySet<School> Schools
		{
			get
			{
				return this._Schools;
			}
			set
			{
				this._Schools.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="District_AreaOffice", Storage="_District", ThisKey="D_No", OtherKey="D_No", IsForeignKey=true)]
		public District District
		{
			get
			{
				return this._District.Entity;
			}
			set
			{
				District previousValue = this._District.Entity;
				if (((previousValue != value) 
							|| (this._District.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._District.Entity = null;
						previousValue.AreaOffices.Remove(this);
					}
					this._District.Entity = value;
					if ((value != null))
					{
						value.AreaOffices.Add(this);
						this._D_No = value.D_No;
					}
					else
					{
						this._D_No = default(string);
					}
					this.SendPropertyChanged("District");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_A_Reports(A_Report entity)
		{
			this.SendPropertyChanging();
			entity.AreaOffice = this;
		}
		
		private void detach_A_Reports(A_Report entity)
		{
			this.SendPropertyChanging();
			entity.AreaOffice = null;
		}
		
		private void attach_AreaSchoolMessages(AreaSchoolMessage entity)
		{
			this.SendPropertyChanging();
			entity.AreaOffice = this;
		}
		
		private void detach_AreaSchoolMessages(AreaSchoolMessage entity)
		{
			this.SendPropertyChanging();
			entity.AreaOffice = null;
		}
		
		private void attach_Schools(School entity)
		{
			this.SendPropertyChanging();
			entity.AreaOffice = this;
		}
		
		private void detach_Schools(School entity)
		{
			this.SendPropertyChanging();
			entity.AreaOffice = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AreaSchoolMessage")]
	public partial class AreaSchoolMessage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _A_No;
		
		private string _Message;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<int> _Type;
		
		private string _Subject;
		
		private int _M_ID;
		
		private EntityRef<AreaOffice> _AreaOffice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnA_NoChanging(string value);
    partial void OnA_NoChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnTypeChanging(System.Nullable<int> value);
    partial void OnTypeChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnM_IDChanging(int value);
    partial void OnM_IDChanged();
    #endregion
		
		public AreaSchoolMessage()
		{
			this._AreaOffice = default(EntityRef<AreaOffice>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_No", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string A_No
		{
			get
			{
				return this._A_No;
			}
			set
			{
				if ((this._A_No != value))
				{
					if (this._AreaOffice.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnA_NoChanging(value);
					this.SendPropertyChanging();
					this._A_No = value;
					this.SendPropertyChanged("A_No");
					this.OnA_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(MAX)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="VarChar(255)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int M_ID
		{
			get
			{
				return this._M_ID;
			}
			set
			{
				if ((this._M_ID != value))
				{
					this.OnM_IDChanging(value);
					this.SendPropertyChanging();
					this._M_ID = value;
					this.SendPropertyChanged("M_ID");
					this.OnM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AreaOffice_AreaSchoolMessage", Storage="_AreaOffice", ThisKey="A_No", OtherKey="A_No", IsForeignKey=true)]
		public AreaOffice AreaOffice
		{
			get
			{
				return this._AreaOffice.Entity;
			}
			set
			{
				AreaOffice previousValue = this._AreaOffice.Entity;
				if (((previousValue != value) 
							|| (this._AreaOffice.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AreaOffice.Entity = null;
						previousValue.AreaSchoolMessages.Remove(this);
					}
					this._AreaOffice.Entity = value;
					if ((value != null))
					{
						value.AreaSchoolMessages.Add(this);
						this._A_No = value.A_No;
					}
					else
					{
						this._A_No = default(string);
					}
					this.SendPropertyChanged("AreaOffice");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.D_Report")]
	public partial class D_Report : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _R_ID;
		
		private System.DateTime _Month;
		
		private System.Nullable<decimal> _BankCharges;
		
		private System.Nullable<decimal> _Allocation;
		
		private System.Nullable<decimal> _Expenditure;
		
		private string _D_No;
		
		private EntityRef<District> _District;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnR_IDChanging(int value);
    partial void OnR_IDChanged();
    partial void OnMonthChanging(System.DateTime value);
    partial void OnMonthChanged();
    partial void OnBankChargesChanging(System.Nullable<decimal> value);
    partial void OnBankChargesChanged();
    partial void OnAllocationChanging(System.Nullable<decimal> value);
    partial void OnAllocationChanged();
    partial void OnExpenditureChanging(System.Nullable<decimal> value);
    partial void OnExpenditureChanged();
    partial void OnD_NoChanging(string value);
    partial void OnD_NoChanged();
    #endregion
		
		public D_Report()
		{
			this._District = default(EntityRef<District>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int R_ID
		{
			get
			{
				return this._R_ID;
			}
			set
			{
				if ((this._R_ID != value))
				{
					this.OnR_IDChanging(value);
					this.SendPropertyChanging();
					this._R_ID = value;
					this.SendPropertyChanged("R_ID");
					this.OnR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Date NOT NULL")]
		public System.DateTime Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this.OnMonthChanging(value);
					this.SendPropertyChanging();
					this._Month = value;
					this.SendPropertyChanged("Month");
					this.OnMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankCharges", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> BankCharges
		{
			get
			{
				return this._BankCharges;
			}
			set
			{
				if ((this._BankCharges != value))
				{
					this.OnBankChargesChanging(value);
					this.SendPropertyChanging();
					this._BankCharges = value;
					this.SendPropertyChanged("BankCharges");
					this.OnBankChargesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Allocation", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Allocation
		{
			get
			{
				return this._Allocation;
			}
			set
			{
				if ((this._Allocation != value))
				{
					this.OnAllocationChanging(value);
					this.SendPropertyChanging();
					this._Allocation = value;
					this.SendPropertyChanged("Allocation");
					this.OnAllocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expenditure", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Expenditure
		{
			get
			{
				return this._Expenditure;
			}
			set
			{
				if ((this._Expenditure != value))
				{
					this.OnExpenditureChanging(value);
					this.SendPropertyChanging();
					this._Expenditure = value;
					this.SendPropertyChanged("Expenditure");
					this.OnExpenditureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_No", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string D_No
		{
			get
			{
				return this._D_No;
			}
			set
			{
				if ((this._D_No != value))
				{
					if (this._District.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnD_NoChanging(value);
					this.SendPropertyChanging();
					this._D_No = value;
					this.SendPropertyChanged("D_No");
					this.OnD_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="District_D_Report", Storage="_District", ThisKey="D_No", OtherKey="D_No", IsForeignKey=true)]
		public District District
		{
			get
			{
				return this._District.Entity;
			}
			set
			{
				District previousValue = this._District.Entity;
				if (((previousValue != value) 
							|| (this._District.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._District.Entity = null;
						previousValue.D_Reports.Remove(this);
					}
					this._District.Entity = value;
					if ((value != null))
					{
						value.D_Reports.Add(this);
						this._D_No = value.D_No;
					}
					else
					{
						this._D_No = default(string);
					}
					this.SendPropertyChanged("District");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.District")]
	public partial class District : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _D_No;
		
		private string _D_Email;
		
		private string _D_Name;
		
		private string _P_No;
		
		private string _D_Tellphone;
		
		private string _D_Cellphone;
		
		private string _D_Manager;
		
		private System.Nullable<int> _D_NumAreas;
		
		private EntitySet<AreaOffice> _AreaOffices;
		
		private EntitySet<D_Report> _D_Reports;
		
		private EntitySet<DistrictAreaMessage> _DistrictAreaMessages;
		
		private EntityRef<Provincial> _Provincial;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnD_NoChanging(string value);
    partial void OnD_NoChanged();
    partial void OnD_EmailChanging(string value);
    partial void OnD_EmailChanged();
    partial void OnD_NameChanging(string value);
    partial void OnD_NameChanged();
    partial void OnP_NoChanging(string value);
    partial void OnP_NoChanged();
    partial void OnD_TellphoneChanging(string value);
    partial void OnD_TellphoneChanged();
    partial void OnD_CellphoneChanging(string value);
    partial void OnD_CellphoneChanged();
    partial void OnD_ManagerChanging(string value);
    partial void OnD_ManagerChanged();
    partial void OnD_NumAreasChanging(System.Nullable<int> value);
    partial void OnD_NumAreasChanged();
    #endregion
		
		public District()
		{
			this._AreaOffices = new EntitySet<AreaOffice>(new Action<AreaOffice>(this.attach_AreaOffices), new Action<AreaOffice>(this.detach_AreaOffices));
			this._D_Reports = new EntitySet<D_Report>(new Action<D_Report>(this.attach_D_Reports), new Action<D_Report>(this.detach_D_Reports));
			this._DistrictAreaMessages = new EntitySet<DistrictAreaMessage>(new Action<DistrictAreaMessage>(this.attach_DistrictAreaMessages), new Action<DistrictAreaMessage>(this.detach_DistrictAreaMessages));
			this._Provincial = default(EntityRef<Provincial>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_No", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string D_No
		{
			get
			{
				return this._D_No;
			}
			set
			{
				if ((this._D_No != value))
				{
					this.OnD_NoChanging(value);
					this.SendPropertyChanging();
					this._D_No = value;
					this.SendPropertyChanged("D_No");
					this.OnD_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_Email", DbType="VarChar(50)")]
		public string D_Email
		{
			get
			{
				return this._D_Email;
			}
			set
			{
				if ((this._D_Email != value))
				{
					this.OnD_EmailChanging(value);
					this.SendPropertyChanging();
					this._D_Email = value;
					this.SendPropertyChanged("D_Email");
					this.OnD_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_Name", DbType="VarChar(50)")]
		public string D_Name
		{
			get
			{
				return this._D_Name;
			}
			set
			{
				if ((this._D_Name != value))
				{
					this.OnD_NameChanging(value);
					this.SendPropertyChanging();
					this._D_Name = value;
					this.SendPropertyChanged("D_Name");
					this.OnD_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_No", DbType="VarChar(50)")]
		public string P_No
		{
			get
			{
				return this._P_No;
			}
			set
			{
				if ((this._P_No != value))
				{
					if (this._Provincial.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnP_NoChanging(value);
					this.SendPropertyChanging();
					this._P_No = value;
					this.SendPropertyChanged("P_No");
					this.OnP_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_Tellphone", DbType="VarChar(50)")]
		public string D_Tellphone
		{
			get
			{
				return this._D_Tellphone;
			}
			set
			{
				if ((this._D_Tellphone != value))
				{
					this.OnD_TellphoneChanging(value);
					this.SendPropertyChanging();
					this._D_Tellphone = value;
					this.SendPropertyChanged("D_Tellphone");
					this.OnD_TellphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_Cellphone", DbType="VarChar(50)")]
		public string D_Cellphone
		{
			get
			{
				return this._D_Cellphone;
			}
			set
			{
				if ((this._D_Cellphone != value))
				{
					this.OnD_CellphoneChanging(value);
					this.SendPropertyChanging();
					this._D_Cellphone = value;
					this.SendPropertyChanged("D_Cellphone");
					this.OnD_CellphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_Manager", DbType="VarChar(50)")]
		public string D_Manager
		{
			get
			{
				return this._D_Manager;
			}
			set
			{
				if ((this._D_Manager != value))
				{
					this.OnD_ManagerChanging(value);
					this.SendPropertyChanging();
					this._D_Manager = value;
					this.SendPropertyChanged("D_Manager");
					this.OnD_ManagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_NumAreas", DbType="Int")]
		public System.Nullable<int> D_NumAreas
		{
			get
			{
				return this._D_NumAreas;
			}
			set
			{
				if ((this._D_NumAreas != value))
				{
					this.OnD_NumAreasChanging(value);
					this.SendPropertyChanging();
					this._D_NumAreas = value;
					this.SendPropertyChanged("D_NumAreas");
					this.OnD_NumAreasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="District_AreaOffice", Storage="_AreaOffices", ThisKey="D_No", OtherKey="D_No")]
		public EntitySet<AreaOffice> AreaOffices
		{
			get
			{
				return this._AreaOffices;
			}
			set
			{
				this._AreaOffices.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="District_D_Report", Storage="_D_Reports", ThisKey="D_No", OtherKey="D_No")]
		public EntitySet<D_Report> D_Reports
		{
			get
			{
				return this._D_Reports;
			}
			set
			{
				this._D_Reports.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="District_DistrictAreaMessage", Storage="_DistrictAreaMessages", ThisKey="D_No", OtherKey="D_No")]
		public EntitySet<DistrictAreaMessage> DistrictAreaMessages
		{
			get
			{
				return this._DistrictAreaMessages;
			}
			set
			{
				this._DistrictAreaMessages.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincial_District", Storage="_Provincial", ThisKey="P_No", OtherKey="P_No", IsForeignKey=true)]
		public Provincial Provincial
		{
			get
			{
				return this._Provincial.Entity;
			}
			set
			{
				Provincial previousValue = this._Provincial.Entity;
				if (((previousValue != value) 
							|| (this._Provincial.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Provincial.Entity = null;
						previousValue.Districts.Remove(this);
					}
					this._Provincial.Entity = value;
					if ((value != null))
					{
						value.Districts.Add(this);
						this._P_No = value.P_No;
					}
					else
					{
						this._P_No = default(string);
					}
					this.SendPropertyChanged("Provincial");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AreaOffices(AreaOffice entity)
		{
			this.SendPropertyChanging();
			entity.District = this;
		}
		
		private void detach_AreaOffices(AreaOffice entity)
		{
			this.SendPropertyChanging();
			entity.District = null;
		}
		
		private void attach_D_Reports(D_Report entity)
		{
			this.SendPropertyChanging();
			entity.District = this;
		}
		
		private void detach_D_Reports(D_Report entity)
		{
			this.SendPropertyChanging();
			entity.District = null;
		}
		
		private void attach_DistrictAreaMessages(DistrictAreaMessage entity)
		{
			this.SendPropertyChanging();
			entity.District = this;
		}
		
		private void detach_DistrictAreaMessages(DistrictAreaMessage entity)
		{
			this.SendPropertyChanging();
			entity.District = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DistrictAreaMessage")]
	public partial class DistrictAreaMessage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _D_No;
		
		private string _Message;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<int> _Type;
		
		private string _Subject;
		
		private int _M_ID;
		
		private EntityRef<District> _District;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnD_NoChanging(string value);
    partial void OnD_NoChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnTypeChanging(System.Nullable<int> value);
    partial void OnTypeChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnM_IDChanging(int value);
    partial void OnM_IDChanged();
    #endregion
		
		public DistrictAreaMessage()
		{
			this._District = default(EntityRef<District>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_No", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string D_No
		{
			get
			{
				return this._D_No;
			}
			set
			{
				if ((this._D_No != value))
				{
					if (this._District.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnD_NoChanging(value);
					this.SendPropertyChanging();
					this._D_No = value;
					this.SendPropertyChanged("D_No");
					this.OnD_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(MAX)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="VarChar(255)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int M_ID
		{
			get
			{
				return this._M_ID;
			}
			set
			{
				if ((this._M_ID != value))
				{
					this.OnM_IDChanging(value);
					this.SendPropertyChanging();
					this._M_ID = value;
					this.SendPropertyChanged("M_ID");
					this.OnM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="District_DistrictAreaMessage", Storage="_District", ThisKey="D_No", OtherKey="D_No", IsForeignKey=true)]
		public District District
		{
			get
			{
				return this._District.Entity;
			}
			set
			{
				District previousValue = this._District.Entity;
				if (((previousValue != value) 
							|| (this._District.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._District.Entity = null;
						previousValue.DistrictAreaMessages.Remove(this);
					}
					this._District.Entity = value;
					if ((value != null))
					{
						value.DistrictAreaMessages.Add(this);
						this._D_No = value.D_No;
					}
					else
					{
						this._D_No = default(string);
					}
					this.SendPropertyChanged("District");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FileInformation")]
	public partial class FileInformation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _ContentType;
		
		private double _ContentLength;
		
		private string _EMIS;
		
		private string _Code;
		
		private EntityRef<School> _School;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnContentTypeChanging(string value);
    partial void OnContentTypeChanged();
    partial void OnContentLengthChanging(double value);
    partial void OnContentLengthChanged();
    partial void OnEMISChanging(string value);
    partial void OnEMISChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    #endregion
		
		public FileInformation()
		{
			this._School = default(EntityRef<School>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ContentType
		{
			get
			{
				return this._ContentType;
			}
			set
			{
				if ((this._ContentType != value))
				{
					this.OnContentTypeChanging(value);
					this.SendPropertyChanging();
					this._ContentType = value;
					this.SendPropertyChanged("ContentType");
					this.OnContentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentLength", DbType="Float NOT NULL")]
		public double ContentLength
		{
			get
			{
				return this._ContentLength;
			}
			set
			{
				if ((this._ContentLength != value))
				{
					this.OnContentLengthChanging(value);
					this.SendPropertyChanging();
					this._ContentLength = value;
					this.SendPropertyChanged("ContentLength");
					this.OnContentLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMIS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMIS
		{
			get
			{
				return this._EMIS;
			}
			set
			{
				if ((this._EMIS != value))
				{
					if (this._School.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEMISChanging(value);
					this.SendPropertyChanging();
					this._EMIS = value;
					this.SendPropertyChanged("EMIS");
					this.OnEMISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(255)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="School_FileInformation", Storage="_School", ThisKey="EMIS", OtherKey="EMIS", IsForeignKey=true)]
		public School School
		{
			get
			{
				return this._School.Entity;
			}
			set
			{
				School previousValue = this._School.Entity;
				if (((previousValue != value) 
							|| (this._School.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._School.Entity = null;
						previousValue.FileInformations.Remove(this);
					}
					this._School.Entity = value;
					if ((value != null))
					{
						value.FileInformations.Add(this);
						this._EMIS = value.EMIS;
					}
					else
					{
						this._EMIS = default(string);
					}
					this.SendPropertyChanged("School");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Provincial")]
	public partial class Provincial : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _P_No;
		
		private string _P_Name;
		
		private string _p_Manageer;
		
		private string _P_Email;
		
		private string _P_Tellphone;
		
		private string _P_Cellphone;
		
		private System.Nullable<int> _Num_Areas;
		
		private System.Nullable<int> _Num_Districts;
		
		private EntitySet<District> _Districts;
		
		private EntitySet<School> _Schools;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnP_NoChanging(string value);
    partial void OnP_NoChanged();
    partial void OnP_NameChanging(string value);
    partial void OnP_NameChanged();
    partial void Onp_ManageerChanging(string value);
    partial void Onp_ManageerChanged();
    partial void OnP_EmailChanging(string value);
    partial void OnP_EmailChanged();
    partial void OnP_TellphoneChanging(string value);
    partial void OnP_TellphoneChanged();
    partial void OnP_CellphoneChanging(string value);
    partial void OnP_CellphoneChanged();
    partial void OnNum_AreasChanging(System.Nullable<int> value);
    partial void OnNum_AreasChanged();
    partial void OnNum_DistrictsChanging(System.Nullable<int> value);
    partial void OnNum_DistrictsChanged();
    #endregion
		
		public Provincial()
		{
			this._Districts = new EntitySet<District>(new Action<District>(this.attach_Districts), new Action<District>(this.detach_Districts));
			this._Schools = new EntitySet<School>(new Action<School>(this.attach_Schools), new Action<School>(this.detach_Schools));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_No", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string P_No
		{
			get
			{
				return this._P_No;
			}
			set
			{
				if ((this._P_No != value))
				{
					this.OnP_NoChanging(value);
					this.SendPropertyChanging();
					this._P_No = value;
					this.SendPropertyChanged("P_No");
					this.OnP_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Name", DbType="VarChar(50)")]
		public string P_Name
		{
			get
			{
				return this._P_Name;
			}
			set
			{
				if ((this._P_Name != value))
				{
					this.OnP_NameChanging(value);
					this.SendPropertyChanging();
					this._P_Name = value;
					this.SendPropertyChanged("P_Name");
					this.OnP_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_Manageer", DbType="VarChar(50)")]
		public string p_Manageer
		{
			get
			{
				return this._p_Manageer;
			}
			set
			{
				if ((this._p_Manageer != value))
				{
					this.Onp_ManageerChanging(value);
					this.SendPropertyChanging();
					this._p_Manageer = value;
					this.SendPropertyChanged("p_Manageer");
					this.Onp_ManageerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Email
		{
			get
			{
				return this._P_Email;
			}
			set
			{
				if ((this._P_Email != value))
				{
					this.OnP_EmailChanging(value);
					this.SendPropertyChanging();
					this._P_Email = value;
					this.SendPropertyChanged("P_Email");
					this.OnP_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Tellphone", DbType="VarChar(50)")]
		public string P_Tellphone
		{
			get
			{
				return this._P_Tellphone;
			}
			set
			{
				if ((this._P_Tellphone != value))
				{
					this.OnP_TellphoneChanging(value);
					this.SendPropertyChanging();
					this._P_Tellphone = value;
					this.SendPropertyChanged("P_Tellphone");
					this.OnP_TellphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Cellphone", DbType="VarChar(50)")]
		public string P_Cellphone
		{
			get
			{
				return this._P_Cellphone;
			}
			set
			{
				if ((this._P_Cellphone != value))
				{
					this.OnP_CellphoneChanging(value);
					this.SendPropertyChanging();
					this._P_Cellphone = value;
					this.SendPropertyChanged("P_Cellphone");
					this.OnP_CellphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Areas", DbType="Int")]
		public System.Nullable<int> Num_Areas
		{
			get
			{
				return this._Num_Areas;
			}
			set
			{
				if ((this._Num_Areas != value))
				{
					this.OnNum_AreasChanging(value);
					this.SendPropertyChanging();
					this._Num_Areas = value;
					this.SendPropertyChanged("Num_Areas");
					this.OnNum_AreasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Districts", DbType="Int")]
		public System.Nullable<int> Num_Districts
		{
			get
			{
				return this._Num_Districts;
			}
			set
			{
				if ((this._Num_Districts != value))
				{
					this.OnNum_DistrictsChanging(value);
					this.SendPropertyChanging();
					this._Num_Districts = value;
					this.SendPropertyChanged("Num_Districts");
					this.OnNum_DistrictsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincial_District", Storage="_Districts", ThisKey="P_No", OtherKey="P_No")]
		public EntitySet<District> Districts
		{
			get
			{
				return this._Districts;
			}
			set
			{
				this._Districts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincial_School", Storage="_Schools", ThisKey="P_No", OtherKey="P_No")]
		public EntitySet<School> Schools
		{
			get
			{
				return this._Schools;
			}
			set
			{
				this._Schools.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Districts(District entity)
		{
			this.SendPropertyChanging();
			entity.Provincial = this;
		}
		
		private void detach_Districts(District entity)
		{
			this.SendPropertyChanging();
			entity.Provincial = null;
		}
		
		private void attach_Schools(School entity)
		{
			this.SendPropertyChanging();
			entity.Provincial = this;
		}
		
		private void detach_Schools(School entity)
		{
			this.SendPropertyChanging();
			entity.Provincial = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.S_Report")]
	public partial class S_Report : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _R_ID;
		
		private string _EMIS;
		
		private System.Nullable<System.DateTime> _Submission_Date;
		
		private string _Month;
		
		private System.Nullable<double> _Food;
		
		private System.Nullable<double> _Greenies;
		
		private System.Nullable<double> _Gas_Wood;
		
		private System.Nullable<double> _Honorarium;
		
		private System.Nullable<double> _BankCharges;
		
		private System.Nullable<double> _Allocation;
		
		private System.Nullable<double> _Expenditure;
		
		private System.Nullable<double> _Balance;
		
		private System.Nullable<int> _NumDays;
		
		private System.Nullable<int> _AvgLearnerFed;
		
		private System.Nullable<double> _AvgBudget;
		
		private System.Nullable<double> _ClosingBalance;
		
		private string _Code;
		
		private EntityRef<School> _School;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnR_IDChanging(int value);
    partial void OnR_IDChanged();
    partial void OnEMISChanging(string value);
    partial void OnEMISChanged();
    partial void OnSubmission_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnSubmission_DateChanged();
    partial void OnMonthChanging(string value);
    partial void OnMonthChanged();
    partial void OnFoodChanging(System.Nullable<double> value);
    partial void OnFoodChanged();
    partial void OnGreeniesChanging(System.Nullable<double> value);
    partial void OnGreeniesChanged();
    partial void OnGas_WoodChanging(System.Nullable<double> value);
    partial void OnGas_WoodChanged();
    partial void OnHonorariumChanging(System.Nullable<double> value);
    partial void OnHonorariumChanged();
    partial void OnBankChargesChanging(System.Nullable<double> value);
    partial void OnBankChargesChanged();
    partial void OnAllocationChanging(System.Nullable<double> value);
    partial void OnAllocationChanged();
    partial void OnExpenditureChanging(System.Nullable<double> value);
    partial void OnExpenditureChanged();
    partial void OnBalanceChanging(System.Nullable<double> value);
    partial void OnBalanceChanged();
    partial void OnNumDaysChanging(System.Nullable<int> value);
    partial void OnNumDaysChanged();
    partial void OnAvgLearnerFedChanging(System.Nullable<int> value);
    partial void OnAvgLearnerFedChanged();
    partial void OnAvgBudgetChanging(System.Nullable<double> value);
    partial void OnAvgBudgetChanged();
    partial void OnClosingBalanceChanging(System.Nullable<double> value);
    partial void OnClosingBalanceChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    #endregion
		
		public S_Report()
		{
			this._School = default(EntityRef<School>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int R_ID
		{
			get
			{
				return this._R_ID;
			}
			set
			{
				if ((this._R_ID != value))
				{
					this.OnR_IDChanging(value);
					this.SendPropertyChanging();
					this._R_ID = value;
					this.SendPropertyChanged("R_ID");
					this.OnR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMIS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMIS
		{
			get
			{
				return this._EMIS;
			}
			set
			{
				if ((this._EMIS != value))
				{
					if (this._School.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEMISChanging(value);
					this.SendPropertyChanging();
					this._EMIS = value;
					this.SendPropertyChanged("EMIS");
					this.OnEMISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Submission_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Submission_Date
		{
			get
			{
				return this._Submission_Date;
			}
			set
			{
				if ((this._Submission_Date != value))
				{
					this.OnSubmission_DateChanging(value);
					this.SendPropertyChanging();
					this._Submission_Date = value;
					this.SendPropertyChanged("Submission_Date");
					this.OnSubmission_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="VarChar(50)")]
		public string Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this.OnMonthChanging(value);
					this.SendPropertyChanging();
					this._Month = value;
					this.SendPropertyChanged("Month");
					this.OnMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Food", DbType="Float")]
		public System.Nullable<double> Food
		{
			get
			{
				return this._Food;
			}
			set
			{
				if ((this._Food != value))
				{
					this.OnFoodChanging(value);
					this.SendPropertyChanging();
					this._Food = value;
					this.SendPropertyChanged("Food");
					this.OnFoodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Greenies", DbType="Float")]
		public System.Nullable<double> Greenies
		{
			get
			{
				return this._Greenies;
			}
			set
			{
				if ((this._Greenies != value))
				{
					this.OnGreeniesChanging(value);
					this.SendPropertyChanging();
					this._Greenies = value;
					this.SendPropertyChanged("Greenies");
					this.OnGreeniesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gas_Wood", DbType="Float")]
		public System.Nullable<double> Gas_Wood
		{
			get
			{
				return this._Gas_Wood;
			}
			set
			{
				if ((this._Gas_Wood != value))
				{
					this.OnGas_WoodChanging(value);
					this.SendPropertyChanging();
					this._Gas_Wood = value;
					this.SendPropertyChanged("Gas_Wood");
					this.OnGas_WoodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Honorarium", DbType="Float")]
		public System.Nullable<double> Honorarium
		{
			get
			{
				return this._Honorarium;
			}
			set
			{
				if ((this._Honorarium != value))
				{
					this.OnHonorariumChanging(value);
					this.SendPropertyChanging();
					this._Honorarium = value;
					this.SendPropertyChanged("Honorarium");
					this.OnHonorariumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankCharges", DbType="Float")]
		public System.Nullable<double> BankCharges
		{
			get
			{
				return this._BankCharges;
			}
			set
			{
				if ((this._BankCharges != value))
				{
					this.OnBankChargesChanging(value);
					this.SendPropertyChanging();
					this._BankCharges = value;
					this.SendPropertyChanged("BankCharges");
					this.OnBankChargesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Allocation", DbType="Float")]
		public System.Nullable<double> Allocation
		{
			get
			{
				return this._Allocation;
			}
			set
			{
				if ((this._Allocation != value))
				{
					this.OnAllocationChanging(value);
					this.SendPropertyChanging();
					this._Allocation = value;
					this.SendPropertyChanged("Allocation");
					this.OnAllocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expenditure", DbType="Float")]
		public System.Nullable<double> Expenditure
		{
			get
			{
				return this._Expenditure;
			}
			set
			{
				if ((this._Expenditure != value))
				{
					this.OnExpenditureChanging(value);
					this.SendPropertyChanging();
					this._Expenditure = value;
					this.SendPropertyChanged("Expenditure");
					this.OnExpenditureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Float")]
		public System.Nullable<double> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this.OnBalanceChanging(value);
					this.SendPropertyChanging();
					this._Balance = value;
					this.SendPropertyChanged("Balance");
					this.OnBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumDays", DbType="Int")]
		public System.Nullable<int> NumDays
		{
			get
			{
				return this._NumDays;
			}
			set
			{
				if ((this._NumDays != value))
				{
					this.OnNumDaysChanging(value);
					this.SendPropertyChanging();
					this._NumDays = value;
					this.SendPropertyChanged("NumDays");
					this.OnNumDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgLearnerFed", DbType="Int")]
		public System.Nullable<int> AvgLearnerFed
		{
			get
			{
				return this._AvgLearnerFed;
			}
			set
			{
				if ((this._AvgLearnerFed != value))
				{
					this.OnAvgLearnerFedChanging(value);
					this.SendPropertyChanging();
					this._AvgLearnerFed = value;
					this.SendPropertyChanged("AvgLearnerFed");
					this.OnAvgLearnerFedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgBudget", DbType="Float")]
		public System.Nullable<double> AvgBudget
		{
			get
			{
				return this._AvgBudget;
			}
			set
			{
				if ((this._AvgBudget != value))
				{
					this.OnAvgBudgetChanging(value);
					this.SendPropertyChanging();
					this._AvgBudget = value;
					this.SendPropertyChanged("AvgBudget");
					this.OnAvgBudgetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosingBalance", DbType="Float")]
		public System.Nullable<double> ClosingBalance
		{
			get
			{
				return this._ClosingBalance;
			}
			set
			{
				if ((this._ClosingBalance != value))
				{
					this.OnClosingBalanceChanging(value);
					this.SendPropertyChanging();
					this._ClosingBalance = value;
					this.SendPropertyChanged("ClosingBalance");
					this.OnClosingBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(255)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="School_S_Report", Storage="_School", ThisKey="EMIS", OtherKey="EMIS", IsForeignKey=true)]
		public School School
		{
			get
			{
				return this._School.Entity;
			}
			set
			{
				School previousValue = this._School.Entity;
				if (((previousValue != value) 
							|| (this._School.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._School.Entity = null;
						previousValue.S_Reports.Remove(this);
					}
					this._School.Entity = value;
					if ((value != null))
					{
						value.S_Reports.Add(this);
						this._EMIS = value.EMIS;
					}
					else
					{
						this._EMIS = default(string);
					}
					this.SendPropertyChanged("School");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.School")]
	public partial class School : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _EMIS;
		
		private string _S_Name;
		
		private System.Nullable<int> _S_Type;
		
		private string _S_PrincipalName;
		
		private string _S_Email;
		
		private string _S_TellNumber;
		
		private string _S_No_learners;
		
		private string _P_No;
		
		private string _S_CellPhone;
		
		private string _A_No;
		
		private System.Nullable<double> _S_Budget;
		
		private EntitySet<FileInformation> _FileInformations;
		
		private EntitySet<S_Report> _S_Reports;
		
		private EntityRef<AreaOffice> _AreaOffice;
		
		private EntityRef<Provincial> _Provincial;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEMISChanging(string value);
    partial void OnEMISChanged();
    partial void OnS_NameChanging(string value);
    partial void OnS_NameChanged();
    partial void OnS_TypeChanging(System.Nullable<int> value);
    partial void OnS_TypeChanged();
    partial void OnS_PrincipalNameChanging(string value);
    partial void OnS_PrincipalNameChanged();
    partial void OnS_EmailChanging(string value);
    partial void OnS_EmailChanged();
    partial void OnS_TellNumberChanging(string value);
    partial void OnS_TellNumberChanged();
    partial void OnS_No_learnersChanging(string value);
    partial void OnS_No_learnersChanged();
    partial void OnP_NoChanging(string value);
    partial void OnP_NoChanged();
    partial void OnS_CellPhoneChanging(string value);
    partial void OnS_CellPhoneChanged();
    partial void OnA_NoChanging(string value);
    partial void OnA_NoChanged();
    partial void OnS_BudgetChanging(System.Nullable<double> value);
    partial void OnS_BudgetChanged();
    #endregion
		
		public School()
		{
			this._FileInformations = new EntitySet<FileInformation>(new Action<FileInformation>(this.attach_FileInformations), new Action<FileInformation>(this.detach_FileInformations));
			this._S_Reports = new EntitySet<S_Report>(new Action<S_Report>(this.attach_S_Reports), new Action<S_Report>(this.detach_S_Reports));
			this._AreaOffice = default(EntityRef<AreaOffice>);
			this._Provincial = default(EntityRef<Provincial>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMIS", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EMIS
		{
			get
			{
				return this._EMIS;
			}
			set
			{
				if ((this._EMIS != value))
				{
					this.OnEMISChanging(value);
					this.SendPropertyChanging();
					this._EMIS = value;
					this.SendPropertyChanged("EMIS");
					this.OnEMISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Name", DbType="VarChar(MAX)")]
		public string S_Name
		{
			get
			{
				return this._S_Name;
			}
			set
			{
				if ((this._S_Name != value))
				{
					this.OnS_NameChanging(value);
					this.SendPropertyChanging();
					this._S_Name = value;
					this.SendPropertyChanged("S_Name");
					this.OnS_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Type", DbType="Int")]
		public System.Nullable<int> S_Type
		{
			get
			{
				return this._S_Type;
			}
			set
			{
				if ((this._S_Type != value))
				{
					this.OnS_TypeChanging(value);
					this.SendPropertyChanging();
					this._S_Type = value;
					this.SendPropertyChanged("S_Type");
					this.OnS_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_PrincipalName", DbType="VarChar(MAX)")]
		public string S_PrincipalName
		{
			get
			{
				return this._S_PrincipalName;
			}
			set
			{
				if ((this._S_PrincipalName != value))
				{
					this.OnS_PrincipalNameChanging(value);
					this.SendPropertyChanging();
					this._S_PrincipalName = value;
					this.SendPropertyChanged("S_PrincipalName");
					this.OnS_PrincipalNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string S_Email
		{
			get
			{
				return this._S_Email;
			}
			set
			{
				if ((this._S_Email != value))
				{
					this.OnS_EmailChanging(value);
					this.SendPropertyChanging();
					this._S_Email = value;
					this.SendPropertyChanged("S_Email");
					this.OnS_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_TellNumber", DbType="VarChar(50)")]
		public string S_TellNumber
		{
			get
			{
				return this._S_TellNumber;
			}
			set
			{
				if ((this._S_TellNumber != value))
				{
					this.OnS_TellNumberChanging(value);
					this.SendPropertyChanging();
					this._S_TellNumber = value;
					this.SendPropertyChanged("S_TellNumber");
					this.OnS_TellNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_No_learners", DbType="VarChar(50)")]
		public string S_No_learners
		{
			get
			{
				return this._S_No_learners;
			}
			set
			{
				if ((this._S_No_learners != value))
				{
					this.OnS_No_learnersChanging(value);
					this.SendPropertyChanging();
					this._S_No_learners = value;
					this.SendPropertyChanged("S_No_learners");
					this.OnS_No_learnersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_No", DbType="VarChar(50)")]
		public string P_No
		{
			get
			{
				return this._P_No;
			}
			set
			{
				if ((this._P_No != value))
				{
					if (this._Provincial.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnP_NoChanging(value);
					this.SendPropertyChanging();
					this._P_No = value;
					this.SendPropertyChanged("P_No");
					this.OnP_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_CellPhone", DbType="VarChar(50)")]
		public string S_CellPhone
		{
			get
			{
				return this._S_CellPhone;
			}
			set
			{
				if ((this._S_CellPhone != value))
				{
					this.OnS_CellPhoneChanging(value);
					this.SendPropertyChanging();
					this._S_CellPhone = value;
					this.SendPropertyChanged("S_CellPhone");
					this.OnS_CellPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_No", DbType="VarChar(50)")]
		public string A_No
		{
			get
			{
				return this._A_No;
			}
			set
			{
				if ((this._A_No != value))
				{
					if (this._AreaOffice.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnA_NoChanging(value);
					this.SendPropertyChanging();
					this._A_No = value;
					this.SendPropertyChanged("A_No");
					this.OnA_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Budget", DbType="Float")]
		public System.Nullable<double> S_Budget
		{
			get
			{
				return this._S_Budget;
			}
			set
			{
				if ((this._S_Budget != value))
				{
					this.OnS_BudgetChanging(value);
					this.SendPropertyChanging();
					this._S_Budget = value;
					this.SendPropertyChanged("S_Budget");
					this.OnS_BudgetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="School_FileInformation", Storage="_FileInformations", ThisKey="EMIS", OtherKey="EMIS")]
		public EntitySet<FileInformation> FileInformations
		{
			get
			{
				return this._FileInformations;
			}
			set
			{
				this._FileInformations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="School_S_Report", Storage="_S_Reports", ThisKey="EMIS", OtherKey="EMIS")]
		public EntitySet<S_Report> S_Reports
		{
			get
			{
				return this._S_Reports;
			}
			set
			{
				this._S_Reports.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AreaOffice_School", Storage="_AreaOffice", ThisKey="A_No", OtherKey="A_No", IsForeignKey=true)]
		public AreaOffice AreaOffice
		{
			get
			{
				return this._AreaOffice.Entity;
			}
			set
			{
				AreaOffice previousValue = this._AreaOffice.Entity;
				if (((previousValue != value) 
							|| (this._AreaOffice.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AreaOffice.Entity = null;
						previousValue.Schools.Remove(this);
					}
					this._AreaOffice.Entity = value;
					if ((value != null))
					{
						value.Schools.Add(this);
						this._A_No = value.A_No;
					}
					else
					{
						this._A_No = default(string);
					}
					this.SendPropertyChanged("AreaOffice");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Provincial_School", Storage="_Provincial", ThisKey="P_No", OtherKey="P_No", IsForeignKey=true)]
		public Provincial Provincial
		{
			get
			{
				return this._Provincial.Entity;
			}
			set
			{
				Provincial previousValue = this._Provincial.Entity;
				if (((previousValue != value) 
							|| (this._Provincial.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Provincial.Entity = null;
						previousValue.Schools.Remove(this);
					}
					this._Provincial.Entity = value;
					if ((value != null))
					{
						value.Schools.Add(this);
						this._P_No = value.P_No;
					}
					else
					{
						this._P_No = default(string);
					}
					this.SendPropertyChanged("Provincial");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FileInformations(FileInformation entity)
		{
			this.SendPropertyChanging();
			entity.School = this;
		}
		
		private void detach_FileInformations(FileInformation entity)
		{
			this.SendPropertyChanging();
			entity.School = null;
		}
		
		private void attach_S_Reports(S_Report entity)
		{
			this.SendPropertyChanging();
			entity.School = this;
		}
		
		private void detach_S_Reports(S_Report entity)
		{
			this.SendPropertyChanging();
			entity.School = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Logins")]
	public partial class Login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Level_ID;
		
		private string _email;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLevel_IDChanging(string value);
    partial void OnLevel_IDChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public Login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Level_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Level_ID
		{
			get
			{
				return this._Level_ID;
			}
			set
			{
				if ((this._Level_ID != value))
				{
					this.OnLevel_IDChanging(value);
					this.SendPropertyChanging();
					this._Level_ID = value;
					this.SendPropertyChanged("Level_ID");
					this.OnLevel_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
