<?xml version="1.0" encoding="utf-8"?><Database Name="NSNP_Database" Class="NSNPDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\localdb;Initial Catalog=NSNP_Database;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NSNP_DatabaseConnectionString1" Provider="System.Data.SqlClient" />
</Database>